osx_image: xcode6.4
language: objective-c
install:
    - gem install cocoapods -v 0.38.2 --no-document

before_script:
    - cd Example
    - pod install

xcode_workspace: LiquidFloatingActionButton.xcworkspace
xcode_scheme: LiquidFloatingActionButton-Example
xcode_sdk: iphonesimulator8.4
